export const SUCCESS_GET_DATA = 'SUCCESS_GET_DATA'
export const LODDING_GET_DATA = 'LODDING_GET_DATA'
export const ERROR_GET_DATA = 'ERROR_GET_DATA'


export const SUCCESS_GET_SINGLE = 'SUCCESS_GET_SINGLE'
export const LODDING_GET_SINGLE = 'LODDING_GET_SINGLE'
export const ERROR_GET_SINGLE = 'ERROR_GET_SINGLE'   


export const SUCCESS_ADD_DATA = "SUCCESS_ADD_DATA"
export const LODDING_ADD_DATA = "LODDING_ADD_DATA"
export const ERROR_ADD_DATA = "ERROR_ADD_DATA"

export const SUCCESS_UPDATE_DATA = 'SUCCESS_UPDATE_DATA'
export const LODDING_UPDATE_DATA = 'LODDING_UPDATE_DATA'
export const ERROR_UPDATE_DATA = 'ERROR_UPDATE_DATA'


export const SUCCESS_DELETE_DATA = 'SUCCESS_DELETE_DATA'
export const LODDING_DELETE_DATA = 'LODDING_DELETE_DATA'
export const ERROR_DELETE_DATA = 'ERROR_DELETE_DATA'

